### PR TITLE
Implement a static site generator

### PR DESCRIPTION
**Pull request by TOTBWF**
## Patch Description
`ssg` is a tiny static site generator written in C99. To compile, simply use:
```
gcc ssg.c -o ssg
```

Running is as simple as
```
./ssg -s src/ -d dest/ -i index.html
```

If the `-i` argument is omitted, it will print the index file to stdout.

## Example output:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="blog.cofree.coffee" />
  <title>blog.cofree.coffee</title>
  
</head>
<body>
  <div id="runner1">SOLOMON'S BLOG</div>
  <div id="runner1b">functional programming, permaculture, math</div>
  <ul>
      <li><a href="dest/2020-10-17-bounded-space-automata.html"><span></span></a></li>
      <li><a href="dest/2020-12-22-finally-modular-arithmetic.html"><span></span></a></li>
      <li><a href="dest/2020-10-16-hello-world.html"><span></span></a></li>
  </ul>
</body>
</html>
```

## Notes
This C code is pretty bad. Namely, we follow the "never free" school of memory management.

### CODE REVIEW

**Comment by solomon-b** [comment]
lmao I love it but i'm getting a seg fault:
```
➜ ./ssg -s src -d dest              
zsh: segmentation fault (core dumped)  ./ssg -s src -d dest
➜ ./ssg -s src -d dest -i index.html
zsh: segmentation fault (core dumped)  ./ssg -s src -d dest -i index.html
```

**Comment by TOTBWF** [comment]
I am good at C.

What happens when we run it through gdb?
```
gdb ./ssg
run -s src -d dest
bt
```

**Comment by solomon-b** [comment]
```
Reading symbols from ./ssg...
(gdb) run -s src/ -d dest/
Starting program: /home/solomon/Development/cofree.coffee/ssg -s src/ -d dest/
Cannot access memory at address 0x5560000055c
Cannot access memory at address 0x55600000554
Cannot access memory at address 0x5560000055c
Cannot access memory at address 0x5560000055c
Cannot access memory at address 0x55600000554
Cannot access memory at address 0x5560000055c
Cannot access memory at address 0x55600000554
Cannot access memory at address 0x5560000055c
Cannot access memory at address 0x55600000554
[Detaching after fork from child process 25715]
/home/solomon/.zsh/plugins/zsh-nix-shell/scripts/buildShellShim.zsh: line 13: 25715 Segmentation fault      (core dumped) bash "$@"
[Inferior 1 (process 25711) exited with code 0213]
(gdb) bt
No stack.
(gdb) 
```

**Comment by solomon-b** [comment]
Any progress on this?

**Comment by TOTBWF** [comment]
Haven't taken the time to try compiling this on a linux box yet, sorry!

**Pull request closed without merging**
